modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/PieKing1215/InvMove/issues"
[[mods]]
modId="invmove"
version="0.4.0"
displayName="InvMove"
displayURL="https://github.com/PieKing1215/InvMove"
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Lets you move while in your inventory
'''

[[dependencies.invmove]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.invmove]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.invmove]]
    modId="cloth-config2"
    mandatory=true
    versionRange="[3.0,)"
    ordering="NONE"
    side="CLIENT"