modLoader="javafml"
loaderVersion="[33,)"
license="GPL v3.0"
issueTrackerURL="https://github.com/PieKing1215/InvMove/issues"
[[mods]]
modId="invmove"
version="0.4.6"
displayName="InvMove"
displayURL="https://github.com/PieKing1215/InvMove"
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Lets you move while in inventories.'''

[[dependencies.invmove]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.invmove]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.invmove]]
    modId="cloth-config"
    mandatory=true
    versionRange="[4.0,)"
    ordering="NONE"
    side="CLIENT"