modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/PieKing1215/InvMove/issues"
[[mods]]
modId="invmove"
version="0.4.3"
displayName="InvMove"
displayURL="https://github.com/PieKing1215/InvMove"
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Lets you move while in inventories.'''

[[dependencies.invmove]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.invmove]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.invmove]]
    modId="cloth-config2"
    mandatory=true
    versionRange="[1.4,)"
    ordering="NONE"
    side="CLIENT"