modLoader="javafml"
loaderVersion="[34,)"
license="LGPL v3.0"
issueTrackerURL="https://github.com/PieKing1215/InvMove-Forge/issues"
[[mods]]
modId="invmove"
version="1.16-0.5.0"
displayName="InvMove"
displayURL="https://github.com/PieKing1215/InvMove-Forge"
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Lets you move while in inventories.'''

[[dependencies.invmove]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.invmove]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.invmove]]
    modId="cloth-config"
    mandatory=true
    versionRange="[4.0,)"
    ordering="NONE"
    side="CLIENT"